name: test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

# Flutter SDK and essential dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI and styling dependencies
  flutter_svg: ^2.0.11
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.3
  flutter_spinkit: ^5.2.1
  pinput: ^5.0.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  ribbon_widget: ^1.0.5
  easy_stepper: ^0.8.5+1
  skeletonizer: ^1.4.2

  # Localization and internationalization
  easy_localization: ^3.0.7


  # Configuration and utilities
  flutter_native_splash: ^2.4.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.1.0

  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  webview_flutter: ^4.10.0

  # Payments
  moyasar: ^2.0.13

  # Maps
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  map_picker: ^0.0.3
  geocoding: ^3.0.0

  # State management and dependency injection
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  get_it: ^8.0.2
  equatable: ^2.0.5

  # Routing and navigation
  go_router: ^14.3.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Utils
  path_provider: ^2.1.5
  image_picker: ^1.1.2


# Dev dependencies
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  change_app_package_name: ^1.4.0
  very_good_analysis: ^6.0.0

flutter_native_splash:
  background_image: "assets/images/Splash.png"


flutter:
  uses-material-design: true

  # Assets used in the project
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/lang/
    - assets/
    - assets/fonts/


  # Fonts used in the project
  fonts:
    - family: SomarRounded
      fonts:
        - asset: assets/fonts/SomarRounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SomarRounded-Black.ttf
          weight: 900
        - asset: assets/fonts/SomarRounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SomarRounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/SomarRounded-Light.ttf
          weight: 300
        - asset: assets/fonts/SomarRounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/SomarRounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/SomarRounded-Thin.ttf
          weight: 100


flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix:
